services:
  api_surrogate_postgres:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    labels:
      - "exclude=true"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  api_surrogate_app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    labels:
      - port=3007
      - "user=${USER}"
      - "description=API surrogate app"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${POSTGRES_CONTAINER_NAME}
    # ports:
    #   - "3007:3007"
    depends_on:
    - api_surrogate_postgres
      
volumes:
  postgres_db:
